import i18n from "../i18n";

export const builtInPluginTextKeys: Record<string, string> = {
  "API Key": "common:pluginText.apiKey",
  "AWS Signature": "common:pluginText.awsSignature",
  "Access Key ID": "common:pluginText.accessKeyId",
  "Access Token": "common:pluginText.accessToken",
  "Access Token Response": "common:pluginText.accessTokenResponse",
  "Access Token URL": "common:pluginText.accessTokenUrl",
  Advanced: "common:pluginText.advanced",
  Algorithm: "common:pluginText.algorithm",
  "Append Query Parameter": "common:pluginText.appendQueryParameter",
  "As Basic Authentication": "common:pluginText.asBasicAuthentication",
  Audience: "common:pluginText.audience",
  "Authentication Method": "common:pluginText.authenticationMethod",
  "Authorization Code": "common:pluginText.authorizationCode",
  "Authorization URL": "common:pluginText.authorizationUrl",
  "Basic Auth": "common:pluginText.basicAuth",
  "Bearer Token": "common:pluginText.bearerToken",
  Behavior: "common:pluginText.behavior",
  "Callback Port": "common:pluginText.callbackPort",
  "Callback Type": "common:pluginText.callbackType",
  "Clear Window Session": "common:pluginText.clearWindowSession",
  "Client Assertion": "common:pluginText.clientAssertion",
  "Client Credentials": "common:pluginText.clientCredentials",
  "Client ID": "common:pluginText.clientId",
  "Client Secret": "common:pluginText.clientSecret",
  "Code Challenge Method": "common:pluginText.codeChallengeMethod",
  "Code Verifier": "common:pluginText.codeVerifier",
  "Consumer Key": "common:pluginText.consumerKey",
  "Consumer Secret": "common:pluginText.consumerSecret",
  "Copy Current Token": "common:pluginText.copyCurrentToken",
  "Delete Token": "common:pluginText.deleteToken",
  Domain: "common:pluginText.domain",
  "Grant Type": "common:pluginText.grantType",
  "Header Name": "common:pluginText.headerName",
  "Header Prefix": "common:pluginText.headerPrefix",
  "Hosted Redirect": "common:pluginText.hostedRedirect",
  "ID Token": "common:pluginText.idToken",
  "ID and Access Token": "common:pluginText.idAndAccessToken",
  Implicit: "common:pluginText.implicit",
  "In Request Body": "common:pluginText.inRequestBody",
  "Insert Header": "common:pluginText.insertHeader",
  "JWT Algorithm": "common:pluginText.jwtAlgorithm",
  "JWT Bearer": "common:pluginText.jwtBearer",
  "JWT Header": "common:pluginText.jwtHeader",
  "JWT Payload": "common:pluginText.jwtPayload",
  "JWT Secret": "common:pluginText.jwtSecret",
  Key: "common:pluginText.key",
  Localhost: "common:pluginText.localhost",
  "NTLM Auth": "common:pluginText.ntlmAuth",
  "OAuth Version": "common:pluginText.oauthVersion",
  "Opening browser for authorization...": "common:pluginText.openingBrowser",
  "Only required if you are using temporary credentials": "common:pluginText.temporaryOnly",
  "Parameter Name": "common:pluginText.parameterName",
  Password: "common:pluginText.password",
  Plain: "common:pluginText.plain",
  Prefix: "common:pluginText.prefix",
  Realm: "common:pluginText.realm",
  "Redirect URI (can be any valid URL)": "common:pluginText.redirectUri",
  Region: "common:pluginText.region",
  "Resource Owner Password Credential": "common:pluginText.resourceOwnerPassword",
  "Response Type": "common:pluginText.responseType",
  Scope: "common:pluginText.scope",
  "Secret Access Key": "common:pluginText.secretAccessKey",
  "Secret is base64 encoded": "common:pluginText.secretBase64",
  "Secret or Private Key": "common:pluginText.secretOrPrivateKey",
  "Send All": "request:request.sendAll",
  "Send Credentials": "common:pluginText.sendCredentials",
  "Service Name": "common:pluginText.serviceName",
  "Session Token": "common:pluginText.sessionToken",
  State: "common:pluginText.state",
  "The name of the header to add to the request": "common:pluginText.headerNameDescription",
  "The name of the query parameter to add to the request":
    "common:pluginText.parameterNameDescription",
  "Token copied to clipboard": "common:pluginText.tokenCopied",
  "Token deleted": "common:pluginText.tokenDeleted",
  "Token for authorization": "common:pluginText.authorizationToken",
  "Token Secret": "common:pluginText.tokenSecret",
  Token: "common:pluginText.token",
  "Use External Browser": "common:pluginText.useExternalBrowser",
  "Use PKCE": "common:pluginText.usePkce",
  Username: "common:pluginText.username",
  Workstation: "common:pluginText.workstation",
  "No token to copy": "common:pluginText.noTokenToCopy",
  "No token to delete": "common:pluginText.noTokenToDelete",
  "Copy as Curl": "common:pluginText.copyAsCurl",
  "Copy as gRPCurl": "common:pluginText.copyAsGrpcurl",
  "Command copied to clipboard": "common:pluginText.commandCopied",
  "No requests in folder": "common:pluginText.noRequestsInFolder",
  Input: "common:pluginText.input",
  Encoding: "common:pluginText.encoding",
  "Plain Text": "common:pluginText.plainText",
  "Encoded Value": "common:pluginText.encodedValue",
  "Input Text": "common:pluginText.inputText",
  "Regular Expression": "common:pluginText.regularExpression",
  "Replacement Text": "common:pluginText.replacementText",
  Flags: "common:pluginText.flags",
  Minimum: "common:pluginText.minimum",
  Maximum: "common:pluginText.maximum",
  "Decimal Places": "common:pluginText.decimalPlaces",
  "Return Format": "common:pluginText.returnFormat",
  "First result": "common:pluginText.firstResult",
  "All results": "common:pluginText.allResults",
  "Join with separator": "common:pluginText.joinWithSeparator",
  Separator: "common:pluginText.separator",
  Query: "common:pluginText.query",
  "Pretty Print": "common:pluginText.prettyPrint",
  Request: "common:pluginText.request",
  "Http Request": "common:pluginText.httpRequest",
  "Param Name": "common:pluginText.paramName",
  "JSONPath or XPath": "common:pluginText.jsonPathOrXPath",
  XPath: "common:pluginText.xpath",
  JSONPath: "common:pluginText.jsonPath",
  "Sending Behavior": "common:pluginText.sendingBehavior",
  "When no responses": "common:pluginText.whenNoResponses",
  Always: "common:pluginText.always",
  "When expired": "common:pluginText.whenExpired",
  "TTL (seconds)": "common:pluginText.ttlSeconds",
  Timestamp: "common:pluginText.timestamp",
  Expression: "common:pluginText.expression",
  "Format String": "common:pluginText.formatString",
  "Cookie Name": "common:pluginText.cookieName",
  Label: "common:pluginText.label",
  "Store Input": "common:pluginText.storeInput",
  Never: "common:pluginText.never",
  Expire: "common:pluginText.expire",
  Forever: "common:pluginText.forever",
  Namespace: "common:pluginText.namespace",
  "Key (defaults to Label)": "common:pluginText.keyDefaultsToLabel",
  "Prompt Title": "common:pluginText.promptTitle",
  "Default Value": "common:pluginText.defaultValue",
  "Input Placeholder": "common:pluginText.inputPlaceholder",
  "Mask Value": "common:pluginText.maskValue",
  File: "common:pluginText.file",
  "Select File": "common:pluginText.selectFile",
  "Trim Whitespace": "common:pluginText.trimWhitespace",
  "Service Account": "common:pluginText.serviceAccount",
  "Desktop App": "common:pluginText.desktopApp",
  "Account Name": "common:pluginText.accountName",
  Vault: "common:pluginText.vault",
  Item: "common:pluginText.item",
  Field: "common:pluginText.field",
  Name: "common:pluginText.name",
  "Namespace UUID": "common:pluginText.namespaceUuid",
  "Encode a value to base64": "common:pluginText.encodeBase64Description",
  "Decode a value from base64": "common:pluginText.decodeBase64Description",
  "Encode a value for use in a URL (percent-encoding)": "common:pluginText.encodeUrlDescription",
  "Decode a percent-encoded URL value": "common:pluginText.decodeUrlDescription",
  "Extract text using a regular expression": "common:pluginText.extractRegexDescription",
  "Replace text using a regular expression": "common:pluginText.replaceRegexDescription",
  "Generate a random number between two values": "common:pluginText.randomNumberDescription",
  "Filter JSON-formatted text using JSONPath syntax": "common:pluginText.filterJsonDescription",
  "Filter XML-formatted text using XPath syntax": "common:pluginText.filterXmlDescription",
  "Format the output as JSON": "common:pluginText.formatJsonDescription",
  "Read the contents of a file as utf-8": "common:pluginText.readFileDescription",
  "Specifies how the file's bytes are decoded into text when read":
    "common:pluginText.fileEncodingDescription",
  "Remove leading and trailing whitespace from the file contents":
    "common:pluginText.trimWhitespaceDescription",
  "Prompt the user for input when sending a request": "common:pluginText.promptDescription",
  "Get a secret": "common:pluginText.getSecretDescription",
  "Read the value of a cookie in the jar, by name": "common:pluginText.readCookieDescription",
  "Optionally filter by domain, useful if multiple cookies with the same name.":
    "common:pluginText.cookieDomainDescription",
  "Read the value of a request header, by name": "common:pluginText.readRequestHeaderDescription",
  "Read the value of a response header, by name": "common:pluginText.readResponseHeaderDescription",
  "Access the entire response body, as text": "common:pluginText.responseBodyDescription",
  "Enter an XPath expression used to filter the results": "common:pluginText.xpathDescription",
  "Enter a JSONPath expression used to filter the results": "common:pluginText.jsonPathDescription",
  "Get the timestamp in seconds": "common:pluginText.timestampSecondsDescription",
  "Get the timestamp in milliseconds": "common:pluginText.timestampMillisecondsDescription",
  "Get the date in ISO8601 format": "common:pluginText.isoDateDescription",
  "Format a date using a dayjs-compatible format string": "common:pluginText.formatDateDescription",
  "Get the offset of a date based on an expression": "common:pluginText.dateOffsetDescription",
  "Import Insomnia workspaces": "common:pluginText.importInsomniaDescription",
  "Import OpenAPI collections": "common:pluginText.importOpenApiDescription",
  "Import postman collections": "common:pluginText.importPostmanDescription",
  "Import cURL commands": "common:pluginText.importCurlDescription",
  '"Hosted Redirect" uses an external Yaak-hosted endpoint. "Localhost" starts a local server to receive the callback.':
    "common:pluginText.hostedRedirectDescription",
  "A JavaScript regular expression. Use a capture group to reference parts of the match in the replacement.":
    "common:pluginText.regexInputDescription",
  "A valid UUID to use as the namespace": "common:pluginText.namespaceUuidDescription",
  "Access a field of the response body using JsonPath or XPath":
    "common:pluginText.responseFieldDescription",
  'Account name can be taken from the sidebar of the 1Password App. Make sure you\'re on the BETA version of the 1Password app and have "Integrate with other apps" enabled in Settings > Developer.':
    "common:pluginText.onePasswordAccountDescription",
  Arguments: "common:pluginText.arguments",
  "Callback Url": "common:pluginText.callbackUrl",
  "Can be a timestamp in milliseconds, ISO string, or anything parseable by JS `new Date()`":
    "common:pluginText.timestampInputDescription",
  "Can be any format that can be parsed by JavaScript new Date(...)":
    "common:pluginText.uuidTimestampDescription",
  "Can be HMAC, PEM or JWK. Make sure you pick the correct algorithm type above.":
    "common:pluginText.oauthSecretDescription",
  "Code snippet copied to clipboard": "common:pluginText.codeSnippetCopied",
  "Compute the HMAC of a value": "common:pluginText.hmacDescription",
  "Escape a JSON string, useful when using the output in JSON values":
    "common:pluginText.escapeJsonDescription",
  "Filter JSONPath": "common:pluginText.filterJsonPath",
  "Filter XPath": "common:pluginText.filterXPath",
  "Format string to describe the output (eg. 'yyyy-MM-dd at HH:mm:ss')":
    "common:pluginText.formatStringDescription",
  "Generate a UUID V1": "common:pluginText.uuidV1Description",
  "Generate a UUID V3": "common:pluginText.uuidV3Description",
  "Generate a UUID V4": "common:pluginText.uuidV4Description",
  "Generate a UUID V5": "common:pluginText.uuidV5Description",
  "Generate a UUID V6": "common:pluginText.uuidV6Description",
  "Generate a UUID V7": "common:pluginText.uuidV7Description",
  "Generate Code Snippet": "common:pluginText.generateCodeSnippet",
  "Get the ID of the currently active environment":
    "common:pluginText.activeEnvironmentIdDescription",
  "Get the ID of the currently active request": "common:pluginText.activeRequestIdDescription",
  "Get the ID of the currently active workspace": "common:pluginText.activeWorkspaceIdDescription",
  "Hash a value to its hexadecimal representation": "common:pluginText.hashDescription",
  "Import postman environment exports": "common:pluginText.importPostmanEnvironmentDescription",
  "JWT secret is base64 encoded": "common:pluginText.jwtSecretBase64",
  Language: "common:pluginText.language",
  Library: "common:pluginText.library",
  "MCP Server connected": "common:pluginText.mcpServerConnected",
  "Merged with auto-generated header fields like alg (e.g., kid)":
    "common:pluginText.jwtHeaderDescription",
  "Modification expression (eg. '-5d +2h 3m'). Available units: y, M, d, h, m, s":
    "common:pluginText.modificationExpressionDescription",
  Nonce: "common:pluginText.nonce",
  "OAuth 1.0": "common:pluginText.oauth1",
  "OAuth 2.0": "common:pluginText.oauth2",
  Preview: "common:pluginText.preview",
  "Private Key (RSA-SHA1)": "common:pluginText.privateKeyRsaSha1",
  "Regular expression flags (g for global, i for case-insensitive, m for multiline, etc.)":
    "common:pluginText.regexFlagsDescription",
  "Remove unnecessary whitespace from a valid JSON string.":
    "common:pluginText.minifyJsonDescription",
  'Resend the request when the latest response is older than this many seconds, or if there are no responses yet. "0" means never expires':
    "common:pluginText.responseTtlDescription",
  "Signature Method": "common:pluginText.signatureMethod",
  'The prefix to use for the Authorization header, which will be of the format "<PREFIX> <TOKEN>".':
    "common:pluginText.bearerPrefixDescription",
  "The region that is receiving the request (defaults to us-east-1)":
    "common:pluginText.awsRegionDescription",
  "The replacement text. Use $1, $2, ... to reference capture groups or $& to reference the entire match.":
    "common:pluginText.regexReplacementDescription",
  "The service that is receiving the request (sts, s3, sqs, ...)":
    "common:pluginText.awsServiceDescription",
  "Token can be generated from the 1Password website by visiting Developer > Service Accounts":
    "common:pluginText.onePasswordTokenDescription",
  "URI the OAuth provider redirects to after authorization. Yaak intercepts this automatically in its embedded browser so any valid URI will work.":
    "common:pluginText.redirectUriDescription",
  Verifier: "common:pluginText.verifier",
  "Yaak official format": "common:pluginText.yaakFormatDescription",
  "NTLM is still in beta. Please submit any issues to [Feedback](https://yaak.app/feedback).":
    "common:pluginText.ntlmBetaDescription",
  "OAuth 1.0 is still in beta. Please submit any issues to [Feedback](https://yaak.app/feedback).":
    "common:pluginText.oauth1BetaDescription",
  "-----BEGIN RSA PRIVATE KEY-----\nPrivate key in PEM format\n-----END RSA PRIVATE KEY-----":
    "common:pluginText.rsaPrivateKeyPlaceholder",
  '"Client Secret" sends client_secret. \n"Client Assertion" sends a signed JWT.':
    "common:pluginText.clientCredentialsMethodDescription",
  "Open authorization URL in your system browser instead of the embedded browser. Useful when the OAuth provider blocks embedded browsers or you need existing browser sessions.":
    "common:pluginText.externalBrowserDescription",
  "Redirect URI to Register": "common:pluginText.redirectUriToRegister",
  'Select which token to send in the "Authorization: Bearer" header. Most APIs expect access_token, but some (like OpenID Connect) require id_token.':
    "common:pluginText.authorizationTokenDescription",
  "Automatically generated when not set": "common:pluginText.automaticallyGenerated",
  "input text": "common:pluginText.inputTextPlaceholder",
  "Enter Value": "common:pluginText.enterValue",
  "Copy to Clipboard": "common:pluginText.copyToClipboard",
  Cancel: "common:cancel",
  "Port for the local callback server. Defaults to 8765 if empty.":
    "common:pluginText.callbackPortDescription",
  "Unable to find NTLM challenge in WWW-Authenticate response headers":
    "common:pluginText.ntlmChallengeNotFound",
};

export function localizePluginText(text: string): string {
  const sent = text.match(/^Sent (\d+) requests?$/);
  if (sent != null) {
    return i18n.t("common:pluginText.sentRequests", { count: Number(sent[1]) });
  }

  const partiallyFailed = text.match(/^Sent (\d+), failed (\d+)$/);
  if (partiallyFailed != null) {
    return i18n.t("common:pluginText.sentAndFailed", {
      sent: Number(partiallyFailed[1]),
      failed: Number(partiallyFailed[2]),
    });
  }

  const failedSnippet = text.match(/^Failed to generate snippet: (.+)$/s);
  if (failedSnippet != null) {
    return i18n.t("common:pluginText.failedToGenerateSnippet", { error: failedSnippet[1] });
  }

  const key = builtInPluginTextKeys[text];
  return key == null ? text : i18n.t(key);
}
